basePath: /
definitions:
  internal_httpapi.createOrderRequest:
    properties:
      amount:
        type: integer
      customer_id:
        type: string
    type: object
  internal_httpapi.orderResponse:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      customer_id:
        type: string
      id:
        type: string
      reason:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Minimal REST API to create orders and read their status. Orchestration
    is handled by Temporal; statuses are persisted in Postgres.
  title: Order Service API
  version: "1.0"
paths:
  /orders:
    post:
      consumes:
      - application/json
      parameters:
      - description: Order payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_httpapi.createOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_httpapi.orderResponse'
        "400":
          description: invalid json
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Create order and start processing workflow
      tags:
      - orders
  /orders/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_httpapi.orderResponse'
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Get order status
      tags:
      - orders
swagger: "2.0"
